sequenceDiagram
	Title: D03. Secuencia Consulta API
    participant User as Usuario
    participant API as API Gateway
    participant AuthC as Auth Controller
    participant ChannelC as Channel Controller
    participant DjangoORM as Django ORM
    participant MySQLDB as MySQL Database
    User->>+API: HTTP Request
    API->>+AuthC: ¿Es valido el token?
    alt es válido
        AuthC-->>API: Token válido   
    else no es válido
        AuthC-->>-API: Token inválido
        API-->>User: HTTP Error Response
    end
    API->>+ChannelC: Obtén lista de canales disponibles
    ChannelC->>+DjangoORM: Consulta canales
    DjangoORM->>+MySQLDB: SQL Query
    MySQLDB-->>-DjangoORM: SQL Query Result
    DjangoORM-->>-ChannelC: Devuelve lista de objetos
    ChannelC-->>-API: Devuelve objeto en formato JSON
    API-->>-User: HTTP JSON Response
