# Generated by Django 3.0.7 on 2020-06-29 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_workspace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspace',
            old_name='organization',
            new_name='parent',
        ),
    ]
