# Generated by Django 3.0.7 on 2020-06-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_auto_20200630_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='groups',
            field=models.ManyToManyField(to='workspaces.Group'),
        ),
    ]
