# Generated by Django 3.0.7 on 2020-07-12 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0012_organization_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_admin', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.Organization')),
                ('people', models.ManyToManyField(related_name='workspace_people', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
