openapi: 3.0.0
info:
  version: 0.6.0
  title: Orion ECS
  description: The public API specification for Orion ECS Command Module
  termsOfService: ""
  contact:
    name: Angel Hurtado
    email: contact@angelxehg.com
    url: "http://angelxehg.com"
  license:
    name: MIT
    url: "https://opensource.org/licenses/MIT"
servers:
  - url: "https://orion-ecs-api.herokuapp.com/api/v1"
    description: Main Heroku Deployment
  - url: "https://127.0.0.1:8000/api/v1"
    description: Local development
paths:
  "/organization/":
    summary: Represents a list of Organizations
    description: This resource path represents an Organization in the platform
    options:
      summary: List organization options
      description: Returns the options for organization
      operationId: optionRoot
      tags:
        - organization
      parameters: []
      responses:
        "200":
          description: List of organization options
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPOption"
    get:
      summary: List all organizations
      description: Returns a list of all organizations
      operationId: listOrganizations
      tags:
        - organization
      parameters: []
      responses:
        "200":
          description: List of all organizations
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Organization"
    post:
      summary: Create an organization
      description: Creates and stores a new organization
      operationId: storeOrganization
      tags:
        - organization
      parameters: []
      requestBody:
        $ref: "#/components/requestBodies/OrganizationRequest"
      responses:
        "201":
          description: Stored an Organization
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Organization"
  "/organization/{id}/":
    summary: Represents a list of Organizations
    description: This resource path represents an Organization in the platform
    parameters:
      - name: id
        in: path
        description: ID of organization
        required: true
        schema:
          type: integer
          format: int64
    get:
      summary: Get an organization
      description: Returns the data of an organization
      operationId: getOrganization
      tags:
        - organization
      parameters: []
      responses:
        "200":
          description: Data of an organization
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Organization"
    put:
      summary: Update an organization
      description: Updates organization data
      operationId: updateOrganization
      tags:
        - organization
      parameters: []
      requestBody:
        $ref: "#/components/requestBodies/OrganizationRequest"
      responses:
        "200":
          description: Updated an Organization
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Organization"
    delete:
      summary: Delete an organization
      description: Deletes an organization
      operationId: deleteOrganization
      tags:
        - organization
      parameters: []
      responses:
        "204":
          description: Deleted organization
components:
  schemas:
    Organization:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    OrganizationForm:
      type: object
      properties:
        name:
          type: string
    HTTPOption:
      type: object
      required:
        - name
        - description
      properties:
        name:
          type: string
          example: Option List
        description:
          type: string
          example: Model view set
  requestBodies:
    OrganizationRequest:
      description: Request body for an organization
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/OrganizationForm"
        application/xml:
          schema:
            $ref: "#/components/schemas/OrganizationForm"
        application/x-www-form-urlencoded:
          schema:
            $ref: "#/components/schemas/OrganizationForm"
        multipart/form-data:
          schema:
            $ref: "#/components/schemas/OrganizationForm"
  links: {}
  callbacks: {}
security: []
