openapi: 3.0.0
info:
  version: 0.6.0
  title: Orion ECS
  description: The public API specification for Orion ECS Command Module
  termsOfService: ""
  contact:
    name: Angel Hurtado
    email: contact@angelxehg.com
    url: "http://angelxehg.com"
  license:
    name: MIT
    url: "https://opensource.org/licenses/MIT"
servers:
  - url: "https://orion-ecs-api.herokuapp.com/api/v1"
    description: Main Heroku Deployment
  - url: "https://127.0.0.1:8000/api/v1"
    description: Local development
paths:
  "/organizations/":
    summary: Represents a list of Organizations
    description: This resource path represents an Organization in the platform
    options:
      summary: List organization options
      description: Returns the options for organization
      operationId: optionOrganizationList
      tags:
        - organizations
      parameters: []
      responses:
        "200":
          description: List of organization options
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPOption"
              examples:
                listOptionExample:
                  $ref: "#/components/examples/listOptionExample"
    get:
      summary: List all organizations
      description: Returns a list of all organizations
      operationId: listOrganizations
      tags:
        - organizations
      parameters: []
      responses:
        "200":
          description: List of all organizations
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Organization"
    post:
      summary: Create an organization
      description: Creates and stores a new organization
      operationId: storeOrganization
      tags:
        - organizations
      parameters: []
      requestBody:
        $ref: "#/components/requestBodies/OrganizationRequest"
      responses:
        "201":
          description: Stored an Organization
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Organization"
  "/organizations/{id}/":
    summary: Represents a list of Organizations
    description: This resource path represents an Organization in the platform
    parameters:
      - name: id
        in: path
        description: ID of organization
        required: true
        schema:
          type: integer
          format: int64
          example: 1
    options:
      summary: List an organization options
      description: Returns the options for organization model
      operationId: optionOrganization
      tags:
        - organizations
      parameters: []
      responses:
        "200":
          description: List of an organization options
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPOption"
              examples:
                listOptionExample:
                  $ref: "#/components/examples/modelOptionExample"
    get:
      summary: Get an organization
      description: Returns the data of an organization
      operationId: getOrganization
      tags:
        - organizations
      parameters: []
      responses:
        "200":
          description: Data of an organization
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Organization"
    put:
      summary: Update an organization
      description: Updates organization data
      operationId: updateOrganization
      tags:
        - organizations
      parameters: []
      requestBody:
        $ref: "#/components/requestBodies/OrganizationRequest"
      responses:
        "200":
          description: Updated an Organization
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Organization"
    delete:
      summary: Delete an organization
      description: Deletes an organization
      operationId: deleteOrganization
      tags:
        - organizations
      parameters: []
      responses:
        "204":
          description: Deleted organization
  "/users/":
    summary: Represents a list of Users
    description: This resource path represents an User in the platform
    options:
      summary: List user options
      description: Returns the options for user
      operationId: optionUserList
      tags:
        - users
      parameters: []
      responses:
        "200":
          description: List of user options
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPOption"
              examples:
                listOptionExample:
                  $ref: "#/components/examples/listOptionExample"
    get:
      summary: List all users
      description: Returns a list of all users
      operationId: listUsers
      tags:
        - users
      parameters: []
      responses:
        "200":
          description: List of all users
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    post:
      summary: Create an user
      description: Creates and stores a new user
      operationId: storeUser
      tags:
        - users
      parameters: []
      requestBody:
        $ref: "#/components/requestBodies/UserRequest"
      responses:
        "201":
          description: Stored an User
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  "/users/{id}/":
    summary: Represents a list of Users
    description: This resource path represents an User in the platform
    parameters:
      - name: id
        in: path
        description: ID of user
        required: true
        schema:
          type: integer
          format: int64
          example: 1
    options:
      summary: List an user options
      description: Returns the options for user model
      operationId: optionUser
      tags:
        - users
      parameters: []
      responses:
        "200":
          description: List of an user options
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPOption"
              examples:
                listOptionExample:
                  $ref: "#/components/examples/modelOptionExample"
    get:
      summary: Get an user
      description: Returns the data of an user
      operationId: getUser
      tags:
        - users
      parameters: []
      responses:
        "200":
          description: Data of an user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    put:
      summary: Update an user
      description: Updates user data
      operationId: updateUser
      tags:
        - users
      parameters: []
      requestBody:
        $ref: "#/components/requestBodies/UserRequest"
      responses:
        "200":
          description: Updated an User
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    delete:
      summary: Delete an user
      description: Deletes an user
      operationId: deleteUser
      tags:
        - users
      parameters: []
      responses:
        "204":
          description: Deleted user
components:
  schemas:
    Organization:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      example:
        id: 1
        name: Nova Organization
    OrganizationForm:
      type: object
      properties:
        name:
          type: string
      example:
        name: Nova Organization
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      example:
        id: 1
        name: Nova User
    UserForm:
      type: object
      properties:
        name:
          type: string
      example:
        name: Nova User
    HTTPOption:
      type: object
      required:
        - name
        - description
      properties:
        name:
          type: string
          example: Option List
        description:
          type: string
          example: Model view set
  requestBodies:
    OrganizationRequest:
      description: Request body for an organization
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/OrganizationForm"
        application/x-www-form-urlencoded:
          schema:
            $ref: "#/components/schemas/OrganizationForm"
        multipart/form-data:
          schema:
            $ref: "#/components/schemas/OrganizationForm"
    UserRequest:
      description: Request body for an user
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/UserForm"
        application/x-www-form-urlencoded:
          schema:
            $ref: "#/components/schemas/UserForm"
        multipart/form-data:
          schema:
            $ref: "#/components/schemas/UserForm"
  examples:
    listOptionExample:
      summary: Example of List Options
      value:
        name: Model Viewset List
        description: Model view set
        renders:
          - "application/json"
          - "text/html"
        parses:
          - "application/json"
          - "application/x-www-form-urlencoded"
          - "multipart/form-data"
        actions:
          POST:
            id:
              type: integer
              required: false
              read_only: true
              label: ID
            name:
              type: string
              required: true
              read_only: false
              label: Name
              max_length: 100
    modelOptionExample:
      summary: Example of Model Options
      value:
        name: Model Viewset Instance
        description: Model view set
        renders:
          - "application/json"
          - "text/html"
        parses:
          - "application/json"
          - "application/x-www-form-urlencoded"
          - "multipart/form-data"
        actions:
          PUT:
            id:
              type: integer
              required: false
              read_only: true
              label: ID
            name:
              type: string
              required: true
              read_only: false
              label: Name
              max_length: 100
  links: {}
  callbacks: {}
security: []
